config/routes.rb
Rails.application.routes.draw do
  authenticate :user, ->(user) { user.role == 'admin' } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  get '/admin' => redirect('/')

  devise_for :users
  
  root 'posts#index'

  resources :users

  #followings
  get '/follows/:id', to: 'follows#show', as: 'follows'
  post '/follow/:id', to: 'follows#create', as: 'follow'
  delete '/unfollow/:id', to: 'follows#destroy', as: 'unfollow'

  resources :posts do
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :commenter, presence: true
  validates :body, presence: true, body: true
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, counter_cache: :likes_count
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  scope :max_likes, -> { Post.all.order(likes_count: :DESC).first(3) }

  has_many_attached :images, dependent: :destroy

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin], _suffix: :role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :avatar

  acts_as_followable
  acts_as_follower
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit::Authorization

  def after_sign_in_path_for(_resource)
    root_path
  end

  def after_sign_out_path_for(_resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email username password password_confirmation avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])

    @following_count = @user.follow_count
    @follower_count = @user.followers_count

    @followings = @user.all_following
    @followers = @user.followers
  end

  def create
    user = User.find(current_user.id)
    followed_user = User.find(params[:id])
    user.follow(followed_user)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    user = User.find(current_user.id)
    followed_user = User.find(params[:id])
    user.stop_following(followed_user)
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  before_action :find_post
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @post.likes.create(user_id: current_user.id)
    end
    redirect_to @post
  end

  def find_like
    @like = @post.likes.find(params[:id])
  end

  def destroy
    if !already_liked?
      flash[:notice] = 'Cannot unlike'
    else
      @like.destroy
    end
    redirect_to post_path(@post)
  end

  private

  def already_liked?
    Like.where(user_id: current_user.id, post_id:
    params[:post_id]).exists?
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.includes(:user).includes(:likes).all.order(created_at: :desc)
    #@top_posts = @posts.sort { |post, other_post| other_post.likes_count <=> post.likes_count } [0..2]
    @top_posts = Post.max_likes
    @posts = @posts.page.per(6)
    authorize @posts

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: { posts: @posts, top_posts: @top_posts } }
    end
  end

  def show
    @post = Post.includes(:user).includes(:likes).find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @post }
    end
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    @post = current_user.posts.new(post_params)
    authorize @post

    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    authorize @post
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post
    @post.destroy
    
    redirect_to root_path, status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, images: [])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  def create
    @user = User.create!(user_params)
    session[:user_id] = @user.id

    # UserMailer.with(user: @user).welcome_email.deliver_now
    redirect_to root_path
  
  end
  
  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :avatar)
  end

  def after_sign_up_path_for(_resource)
    root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.includes(:posts).includes(:follows).find(params[:id])

    @following_posts = Post.includes(:user).where('user_id' => @user.all_following)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ror</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;400;500;700;900&display=swap" rel="stylesheet"> 
    <script src="https://kit.fontawesome.com/d285ddef5b.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div class="container">
      <%= yield %>
    </div>
    
    <%= render "shared/footer" %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with :html => {:multipart => true}, model: @post do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
     <% @post.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
 
    <%= form.file_field :images,  multiple: true %>
    <% @post.errors.full_messages_for(:images).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

    <button class=""><%= form.submit %></button>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
    <a class="text-black" href="<%= post_path(post) %>">
        <div class="bg-slate-50 flex gap-4 rounded p-4">
            <h2 class="post-title"><%=post.title%></h2>
            <%= image_tag post.images.first.representation(resize_to_limit: [1024, 400]), :class=>"post-preview-image rounded-4 width-full object-fit-cover" %>
            <p><%= post.likes.count %> <i class="fa-solid fa-heart"></i></p>
            <p class="text-slate-500 width-full" style="word-wrap: break-word;"><%= truncate(post.body) %></p>

            <div class="author-container flex row">
                <%= image_tag post.user.avatar.variant(
                    resize_to_limit: [50, 50], 
                        format: :jpeg, 
                        sampling_factor: "4:2:0", 
                        strip: true, 
                        interlace: "JPEG", 
                        colorspace: "sRGB", 
                        quality: 80), :class=>"rounded-full small-avatar" %>
                
                <p class="text-black"><%= post.user.username %></p>
            </div>
        </div>
    </a>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<h2>Top posts</h2>
  <div class="posts-container">
    <% @top_posts.each do |post|%>
      <%= render 'post', post: post %>
    <%end%>
  </div>

<h2>All posts</h2>
  <div class="posts-container">
    <% @posts.each do |post|%>
        <%= render 'post', post: post %>
    <%end%>
  </div>

<%= paginate @posts %>


<%= link_to "Добавить пост", new_post_path, :class=>"add-post-btn" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
  <h1><%= @post.title %></h1>
    <ul class="image-grid none-left-padding" style="list-style-type:none">
        <% @post.images.each do |file| %>
        <li>
          <% if file.representable? %>
            <%= image_tag file.representation(resize_to_limit: [1024, 400]), :class=>"rounded-4 width-full object-fit-cover" %>
          <% else %>
            <%= link_to rails_blob_path(file, disposition: "attachment") do %>
              <%= image_tag "placeholder.png", alt: "Download file" %>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
<p><%= @post.user.followers_count %>Follower</p>

<% if current_user.following?(@post.user) %>
  <%= button_to 'Unfollow', unfollow_path(@post.user.id), method: :delete %>
<% else %>
  <%= button_to 'Follow', follow_path(@post.user.id), method: :post %>
<% end %>

<p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
    <% if pre_like %>
      <%= button_to 'Unlike post', post_like_path(@post, pre_like), method: :delete %>
    <% else %>
      <%= button_to 'Like post', post_likes_path(@post), method: :post %>
    <% end %>
  
  
  <p><%= @post.body %></p>

  <a class="link-to-profile" href="<%= user_path(@post.user) %>">
    <%= image_tag @post.user.avatar.variant(resize_to_limit: [100, 100]), :class => "small-avatar" %>
    <p><%= @post.user.username %></p>
  </a>
  <% if current_user == @post.user || current_user.role == "admin"%>
    <ul class="flex gap-4">
        <li class="underline"><%= link_to "Редактировать", edit_post_path(@post)%></li>
        <li class="underline"><%= link_to "Удалить", post_path(@post), data: {
                          turbo_method: :delete,
                          turbo_confirm: "Are you sure?"
                        } %></li>
    </ul>
  <% end %>

<% if @post.comments.any? %>
  <h2>Comments</h2>
  <%= render @post.comments %> 
<%end%>
<h2>Add a comment:</h2>
<%= form_with model: [ @post, @post.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
  <% end %>

app/views/shared/_footer.html.erb
<footer>
    <div class="footer-container">
        <div class="footer-text">
        <p>© 2022 Все права защищены</p>
        </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<header style="width: auto">
<div class="nav flex">
    <div class="site-logo">
    <a href="/"><%= image_tag "LogoSample_ByTailorBrands.jpg"%></a> 
    </div>
    <p class="navbar-text">
    <%= link_to "Пользователи", users_path(), :class => 'navbar-link', :style => 'margin-right: 10px' %>
    <% if user_signed_in? %>
        Logged in as <strong><%= current_user.username %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
</div>
</header>

app/views/users/index.html.erb
    <div class="container">
    <h2>Список пользователей</h2>
    <ul class="users-list">
        <% @users.each do |user|%>
            <li>
                <div class="user-card">
                    <a class="text-black" href="<%= user_path(user) %>">
                        <%= image_tag user.avatar.variant(resize_to_limit: [100, 100]), :class => "small-avatar" %>
                        <p><%= user.username %></p>
                    </a>
                </div>
            </li>        
        <%end%>
    </ul>
</div>

app/views/users/show.html.erb
<div class="container user-profile">

    <div class="user-info">
        <p>Профиль пользователя:</p>
        <h3><%= @user.username %></h3>


        <%= image_tag @user.avatar.variant(resize_to_limit: [200, 200]), :class => "small-avatar" %>
        <p>Email: <%= @user.email%></p>
        <p><%= @user.followers_count %>Follower</p>

        <% if current_user.following?(@user) %>
        <%= button_to 'Unfollow', unfollow_path(@user.id), method: :delete %>
        <% else %>
        <%= button_to 'Follow', follow_path(@user.id), method: :post %>
        <% end %>

        <%= link_to "Back", :back %>
    </div>

    <div class="user-posts">
        <h2>Посты пользователя</h2>
                    <ul>
            
            <% @user.posts.each do |post| %>
            <li class="post bg-grey">
                <a class="text-black underline" href="<%= post_path(post) %>">
                    <div class="bg-slate-50 flex flex-col gap-4 rounded p-4">
                        <h3 class="text-black"><%=post.title%></h3>
                        <%= image_tag post.images[0].representation(resize_to_limit: [1024, 400]), :class=>"rounded-4 width-full object-fit-cover" %>           
                        <p class="text-slate-500"><%=post.body%></p>
                        <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
                        <div class="flex items-center gap-2">
                        <%= image_tag @user.avatar.representation(resize_to_limit: [100, 100]), :class=>"rounded-full small-avatar" %>
                        <p class=" text-black"><%= post.user.username %></p>
                        </div>
                    </div>
                </a>
            </li>
            <%end%>
        </ul>
    
    </div>

    <div class="user-followed-posts">
        <h2>Лента</h2>
            <ul>
            
            <% @following_posts.each do |post| %>
            <li class="post bg-grey">
                <a class="text-black underline" href="<%= post_path(post) %>">
                    <div class="bg-slate-50 flex flex-col gap-4 rounded p-4">
                        <h3 class="text-black"><%=post.title%></h3>
                        <%= image_tag post.images[0].representation(resize_to_limit: [1024, 400]), :class=>"rounded-4 width-full object-fit-cover" %>           
                        <p class="text-slate-500"><%=post.body%></p>
                        <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
                        <div class="flex items-center gap-2">
                        <%= image_tag @user.avatar.representation(resize_to_limit: [100, 100]), :class=>"rounded-full small-avatar" %>
                        <p class=" text-black"><%= post.user.username %></p>
                        </div>
                    </div>
                </a>
            </li>
            <%end%>
        </ul>

    </div>    
</div>